### ISSUE TITLE
Unable to build on Kali(3.12-kali1-686-pae)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WebcamStudio/webcamstudio#111]
```
What steps will reproduce the problem?
1. download latest beta
2. dpkg -i webcamstudio.deb

What is the expected output?

Successful installation.

What do you see instead?

root@kali:~/Downloads# dpkg -i webcamstudio_0.57beta4_all.deb 
(Reading database ... 368398 files and directories currently installed.)
Preparing to replace webcamstudio 0.57beta4 (using 
webcamstudio_0.57beta4_all.deb) ...
Unpacking replacement webcamstudio ...
Setting up webcamstudio (0.57beta4) ...
Removing the webcamstudio module from memory
Error: Module webcamstudio is not currently loaded
Removing webcamstudio.ko from the modules
rm: cannot remove 
`/lib/modules/3.12-kali1-686-pae/kernel/drivers/misc/webcamstudio.ko': No such 
file or directory
Restating the webcamstudio service to update the module
[ ok ] Stopping WebcamStudio kernel module: webcamstudio.
[....] Starting WebcamStudio kernel module: webcamstudioBuilding webcamstudio 
driver...
make -C /lib/modules/`uname -r`/build M=/tmp/webcamstudio-src modules
make[1]: Entering directory `/usr/src/linux-headers-3.12-kali1-686-pae'
  CC [M]  /tmp/webcamstudio-src/webcamstudio.o
/tmp/webcamstudio-src/webcamstudio.c: In function ‘init_buffers’:
/tmp/webcamstudio-src/webcamstudio.c:1438:6: error: ‘struct v4l2_buffer’ 
has no member named ‘input’
/tmp/webcamstudio-src/webcamstudio.c: In function ‘init_vdev’:
/tmp/webcamstudio-src/webcamstudio.c:1459:7: error: ‘struct video_device’ 
has no member named ‘current_norm’
/tmp/webcamstudio-src/webcamstudio.c: At top level:
/tmp/webcamstudio-src/webcamstudio.c:1551:3: warning: initialization from 
incompatible pointer type [enabled by default]
/tmp/webcamstudio-src/webcamstudio.c:1551:3: warning: (near initialization for 
‘webcamstudio_ioctl_ops.vidioc_s_std’) [enabled by default]
make[4]: *** [/tmp/webcamstudio-src/webcamstudio.o] Error 1
make[3]: *** [_module_/tmp/webcamstudio-src] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.12-kali1-686-pae'
make: *** [webcamstudio] Error 2
make -C /lib/modules/`uname -r`/build M=/tmp/webcamstudio-src modules_install
make[1]: Entering directory `/usr/src/linux-headers-3.12-kali1-686-pae'
  DEPMOD  3.12-kali1-686-pae
make[1]: Leaving directory `/usr/src/linux-headers-3.12-kali1-686-pae'
depmod -ae
WARNING: -e needs -E or -F
gcc: error: unrecognized command line option ‘-Wl’
cp: cannot stat `libwebcamstudio.so.1.0.1': No such file or directory

[FAIL] Modprobe webcamstudio failed. Please use 'dmesg' to find out why. ... 
failed!
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
root@kali:~#
root@kali:~# dmesg | tail
[   25.131798] wlan0: send auth to 00:1d:7e:d9:cc:8a (try 1/3)
[   25.134026] wlan0: authenticated
[   25.136540] wlan0: associate with 00:1d:7e:d9:cc:8a (try 1/3)
[   25.157174] wlan0: RX AssocResp from 00:1d:7e:d9:cc:8a (capab=0x401 status=0 
aid=1)
[   25.157266] wlan0: associated
[   25.157288] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   26.368145] ACPI Error: Needed [Integer/String/Buffer], found [Reference] 
f690dba8 (20130725/exresop-422)
[   26.368153] ACPI Exception: AE_AML_OPERAND_TYPE, While resolving operands 
for [OpcodeName unavailable] (20130725/dswexec-461)
[   26.368158] ACPI Error: Method parse/execution failed [\_SB_.PCI0.VGA_.AF03] 
(Node f7453818), AE_AML_OPERAND_TYPE (20130725/psparse-536)
[   26.368166] ACPI Error: Method parse/execution failed [\_SB_.PCI0.VGA_.ATIF] 
(Node f7453998), AE_AML_OPERAND_TYPE (20130725/psparse-536)


The Operating system you are using (Linux, Windows etc)?
Linux kali 3.12-kali1-686-pae #1 SMP Debian 3.12.6-2kali1 (2014-01-06) i686 
GNU/Linux

What version of WebcamStudio are you using?
webcamstudio_0.57beta4

What version of Java are you using?
root@kali:~# java -version
java version "1.6.0_31"
OpenJDK Runtime Environment (IcedTea6 1.13.3) (6b31-1.13.3-1~deb7u1)
OpenJDK Server VM (build 23.25-b01, mixed mode)

Both are installed, can be changed to 1.7 if needed.

What is your Webcamera vendor, model and version?

Built in to Samsung NP365E5C-S05US Laptop

For *nix users please enter the output from "sudo lsusb"?
root@kali:~# lsusb
Bus 003 Device 004: ID 2232:1029  
Bus 003 Device 002: ID 0bda:0129 Realtek Semiconductor Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 0cf3:3004 Atheros Communications, Inc. 
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1532:000a Razer USA, Ltd 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub




```

Original issue reported on code.google.com by `0xicl...@gmail.com` on 20 May 2014 at 2:10
