### ISSUE TITLE
Build fails with many errors and warnings

### ISSUE THREAD

**Issue by yurivict** [WebcamStudio/webcamstudio#126]
Build with openjdk8-8.131.11 produces many errors and warnings, for example:

```
  [javadoc] /tmp/webcamstudio/src/webcamstudio/streams/Stream.java:964: error: @param name not found
  [javadoc]      * @param y the y to set
  [javadoc]               ^
  [javadoc] /tmp/webcamstudio/src/webcamstudio/streams/Stream.java:975: error: @param name not found
  [javadoc]      * @param x the x to set
  [javadoc]               ^
  [javadoc] /tmp/webcamstudio/src/com/jhlabs/image/ArrayColormap.java:104: error: malformed HTML
  [javadoc]      * firstIndex < index < lastIndex must hold.
  [javadoc]                   ^
```
